# Generated by Django 4.2.7 on 2024-02-28 13:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('full_address', models.CharField(max_length=90, verbose_name='Полный адрес')),
                ('post_index', models.CharField(max_length=5, verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('card_number', models.CharField(max_length=19, verbose_name='Номер карты')),
                ('expiry_date', models.CharField(max_length=5, verbose_name='Дата истечения срока')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('cardholder_name', models.CharField(max_length=25, verbose_name='Имя на карте')),
                ('time_payment', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 19, 29, 39, 944289), verbose_name='Дата и время оплаты')),
                ('cart', models.JSONField(null=True, verbose_name='Товары')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='Итоговая цена')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
