# Generated by Django 4.2.7 on 2023-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('full_address', models.CharField(max_length=90, verbose_name='Полный адрес')),
                ('post_index', models.IntegerField(verbose_name='Почтовый индекс')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('expiry_date', models.CharField(max_length=5, verbose_name='Дата истечения срока')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('cardholder_name', models.CharField(max_length=25, verbose_name='Имя владельца карты')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оплаты')),
            ],
        ),
    ]
