# Generated by Django 4.2.7 on 2023-12-14 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdata',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='post_index',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Почтовый индекс'),
        ),
    ]
