# Generated by Django 4.2.7 on 2024-02-28 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='time_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 19, 30, 14, 256741), verbose_name='Дата и время оплаты'),
        ),
    ]
