# Generated by Django 4.2.7 on 2023-12-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentdata_card_number_alter_paymentdata_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='card_number',
            field=models.CharField(max_length=19, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='cvv',
            field=models.CharField(max_length=3, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='post_index',
            field=models.CharField(max_length=5, verbose_name='Почтовый индекс'),
        ),
    ]
