# Generated by Django 4.2.7 on 2023-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentdata_card_number_alter_paymentdata_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='cart',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='cardholder_name',
            field=models.CharField(max_length=25, verbose_name='Имя на карте'),
        ),
    ]
