# Generated by Django 4.2.7 on 2023-12-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentdata_total_price_alter_paymentdata_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdata',
            old_name='payment_date',
            new_name='time_payment',
        ),
    ]
