# Generated by Django 4.2.7 on 2024-03-19 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_paymentdata_time_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='time_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 13, 7, 59, 696238), verbose_name='Дата и время оплаты'),
        ),
    ]
