# Generated by Django 4.2.7 on 2024-01-15 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_paymentdata_time_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='time_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 17, 52, 13, 220190), verbose_name='Дата и время оплаты'),
        ),
    ]
