# Generated by Django 4.2.7 on 2024-01-21 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_paymentdata_time_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='time_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 14, 15, 0, 769690), verbose_name='Дата и время оплаты'),
        ),
    ]
