# Generated by Django 4.2.7 on 2024-01-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='сategory',
            new_name='cat',
        ),
    ]
