# Generated by Django 4.2.7 on 2024-01-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_сategory_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ManyToManyField(null=True, to='catalog.productcategory', verbose_name='Категория'),
        ),
    ]
